## Простые типы данных

In [33]:
#задача1
#сначала я преобразовала строку так, чтобы убрать сокращения, так как они воспринимаются как конец строки
string_01 = 'Mama, just killed a man, put a gun against his head, pulled my trigger, now he is dead. Mama, life had just begun, but now I have gone and thrown it all away. Mama, ooh (any way the wind blows), did not mean to make you cry. If I am not back again this time tomorrow carry on, carry on as if nothing really matters.'

In [37]:
#количество слов
len(string_01.split(' '))

65

In [38]:
#количество символов
len(string_01.replace(' ',''))

251

In [31]:
#Задача3
list_01 = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610]

In [32]:
sum([el for el in list_01 if el > 10 and el < 100])

212

In [39]:
#задача4
students = [
 ["0001", "Антонов", "Антон", "Игоревич", "20.08.2009",
"БСТ161"],
 ["1102", "Богов", "Артем", "Игоревич", "25.01.2010",
"БСТ162"],
 ["0333", "Глаголева", "Анастасия", "Николаевна",
"11.07.2009", "БСТ163"],
 ["4004", "Степанова", "Наталья", "Александровна",
"13.02.2008", "БСТ161"],
 ["0045", "Боков", "Игорь", "Харитонович", "02.06.2009",
"БСТ161"],
 ["0096", "Васильков", "Валентин", "Сергеевич", "20.03.2009",
"БСТ164"],
 ["0607", "Сиропова", "Виолетта", "Эдуардовна", "28.05.2010",
"БСТ162"],
 ["0309", "Шафутинский", "Михаил", "Михайлович",
"03.09.2007", "БСТ163"]
 ]

In [46]:
students_1 = {}
for element in students:
    students_1[element[0]] = element[1:]
    print(students_1)

{'0001': ['Антонов', 'Антон', 'Игоревич', '20.08.2009', 'БСТ161']}
{'0001': ['Антонов', 'Антон', 'Игоревич', '20.08.2009', 'БСТ161'], '1102': ['Богов', 'Артем', 'Игоревич', '25.01.2010', 'БСТ162']}
{'0001': ['Антонов', 'Антон', 'Игоревич', '20.08.2009', 'БСТ161'], '1102': ['Богов', 'Артем', 'Игоревич', '25.01.2010', 'БСТ162'], '0333': ['Глаголева', 'Анастасия', 'Николаевна', '11.07.2009', 'БСТ163']}
{'0001': ['Антонов', 'Антон', 'Игоревич', '20.08.2009', 'БСТ161'], '1102': ['Богов', 'Артем', 'Игоревич', '25.01.2010', 'БСТ162'], '0333': ['Глаголева', 'Анастасия', 'Николаевна', '11.07.2009', 'БСТ163'], '4004': ['Степанова', 'Наталья', 'Александровна', '13.02.2008', 'БСТ161']}
{'0001': ['Антонов', 'Антон', 'Игоревич', '20.08.2009', 'БСТ161'], '1102': ['Богов', 'Артем', 'Игоревич', '25.01.2010', 'БСТ162'], '0333': ['Глаголева', 'Анастасия', 'Николаевна', '11.07.2009', 'БСТ163'], '4004': ['Степанова', 'Наталья', 'Александровна', '13.02.2008', 'БСТ161'], '0045': ['Боков', 'Игорь', 'Харитонович', '02.06.2009', 'БСТ161']}
{'0001': ['Антонов', 'Антон', 'Игоревич', '20.08.2009', 'БСТ161'], '1102': ['Богов', 'Артем', 'Игоревич', '25.01.2010', 'БСТ162'], '0333': ['Глаголева', 'Анастасия', 'Николаевна', '11.07.2009', 'БСТ163'], '4004': ['Степанова', 'Наталья', 'Александровна', '13.02.2008', 'БСТ161'], '0045': ['Боков', 'Игорь', 'Харитонович', '02.06.2009', 'БСТ161'], '0096': ['Васильков', 'Валентин', 'Сергеевич', '20.03.2009', 'БСТ164']}
{'0001': ['Антонов', 'Антон', 'Игоревич', '20.08.2009', 'БСТ161'], '1102': ['Богов', 'Артем', 'Игоревич', '25.01.2010', 'БСТ162'], '0333': ['Глаголева', 'Анастасия', 'Николаевна', '11.07.2009', 'БСТ163'], '4004': ['Степанова', 'Наталья', 'Александровна', '13.02.2008', 'БСТ161'], '0045': ['Боков', 'Игорь', 'Харитонович', '02.06.2009', 'БСТ161'], '0096': ['Васильков', 'Валентин', 'Сергеевич', '20.03.2009', 'БСТ164'], '0607': ['Сиропова', 'Виолетта', 'Эдуардовна', '28.05.2010', 'БСТ162']}
{'0001': ['Антонов', 'Антон', 'Игоревич', '20.08.2009', 'БСТ161'], '1102': ['Богов', 'Артем', 'Игоревич', '25.01.2010', 'БСТ162'], '0333': ['Глаголева', 'Анастасия', 'Николаевна', '11.07.2009', 'БСТ163'], '4004': ['Степанова', 'Наталья', 'Александровна', '13.02.2008', 'БСТ161'], '0045': ['Боков', 'Игорь', 'Харитонович', '02.06.2009', 'БСТ161'], '0096': ['Васильков', 'Валентин', 'Сергеевич', '20.03.2009', 'БСТ164'], '0607': ['Сиропова', 'Виолетта', 'Эдуардовна', '28.05.2010', 'БСТ162'], '0309': ['Шафутинский', 'Михаил', 'Михайлович', '03.09.2007', 'БСТ163']}

In [85]:
def change_number():
    num_student = input('Введите номер студента: ')
    if num_student not in students_1.keys():
        print('Номер не найден')
        return
    new_num_group = input('Введите новый номер группы: ')
    for value in students_1.values():
        if num_student in students_1.keys():
            value[-1] = new_num_group
            print('Номер группы изменен')
            print(students_1)
            return

In [86]:
change_number()

Введите номер студента: 0001
Введите новый номер группы: 6
Номер группы изменен
{'0001': ['Антонов', 'Антон', 'Игоревич', '20.08.2009', '6'], '1102': ['Богов', 'Артем', 'Игоревич', '25.01.2010', 'БСТ162'], '0333': ['Глаголева', 'Анастасия', 'Николаевна', '11.07.2009', 'БСТ163'], '4004': ['Степанова', 'Наталья', 'Александровна', '13.02.2008', 'БСТ161'], '0045': ['Боков', 'Игорь', 'Харитонович', '02.06.2009', 'БСТ161'], '0096': ['Васильков', 'Валентин', 'Сергеевич', '20.03.2009', 'БСТ164'], '0607': ['Сиропова', 'Виолетта', 'Эдуардовна', '28.05.2010', 'БСТ162'], '0309': ['Шафутинский', 'Михаил', 'Михайлович', '03.09.2007', 'БСТ163']}

In [87]:
def list_student():
    num_group = input('Введите номер группы: ')
    for value in students_1.values():
        if num_group == value[-1]:
            print(list(value[:3]))
            return

In [88]:
list_student()

Введите номер группы: БСТ163
['Глаголева', 'Анастасия', 'Николаевна']